// musicPlayer-vue/src/MusicPlayer.vue
<template>
  <div :class="['musicContainer', { isPlay }]">
    <div class="musicInfo">
      <div class="musicTitle">{{ curMusic.title }}</div>
      <div class="progressContainer" ref="progressContainer" @click="setProgress">
        <div class="progress" :style="{ width: curProgress }"></div>
      </div>
    </div>
    <div class="musicCover">
      <img :src="curMusic.cover" alt="" />
    </div>
    <div class="musicControls">
      <div class="actionBtn" @click="changeSong('pre')">
        <i class="fas fa-backward"></i>
      </div>
      <div :class="['actionBtn', 'actionBtnBig']" @click="playSong">
        <i :class="`fas ${isPlay ? 'fa-pause' : 'fa-play'}`"></i>
      </div>
      <div class="actionBtn" @click="changeSong('next')">
        <i class="fas fa-forward"></i>
      </div>
    </div>
    <audio ref="audio" :src="curMusic.link" @timeupdate="updateProgress" @ended="changeSong('next')"></audio>
  </div>
</template>

<script>
const musicList = [
  {
    title: '打上花火',
    link: 'db/music/打上花火.mp3',
    cover: 'db/img/打上花火.jpg'
  },
  {
    title: 'Mojito',
    link: 'db/music/Mojito.mp3',
    cover: 'db/img/Mojito.jpg'
  },
  {
    title: 'Super_Star',
    link: 'db/music/Super_Star.mp3',
    cover: 'db/img/Super_Star.jpg'
  },
  {
    title: '离人',
    link: 'db/music/离人.mp3',
    cover: 'db/img/离人.jpg'
  },
]
export default {
  data() {
    return {
      isPlay: false,
      curMusic: {},
      curIndex: 0,
      curProgress: '0%',
    };
  },
  methods: {
    playSong() {
      const audio = this.$refs.audio;
      this.isPlay ? audio.pause() : audio.play()
      this.isPlay = !this.isPlay;
    },
    changeSong(cmd) {
      if (cmd === 'pre') {
        this.curIndex--
        if (this.curIndex < 0) this.curIndex = musicList.length - 1
      }
      else if (cmd === 'next') {
        this.curIndex = (this.curIndex + 1) % musicList.length
      }
      this.curMusic = musicList[this.curIndex]
      if (cmd ==='cur') return
      
      this.isPlay = true
      this.$nextTick(() => {
        this.$refs.audio.play();
      });
    },
    updateProgress(e) {
      const { duration, currentTime } = e.target;
      const progressPercent = (currentTime / duration) * 100;
      this.curProgress = `${progressPercent}%`;
    },
    setProgress(e) {
      const width = this.$refs.progressContainer.clientWidth;
      const clickX = e.offsetX;
      const duration = this.$refs.audio.duration;
      this.$refs.audio.currentTime = (clickX / width) * duration;
    },
  },
  mounted() {
    this.changeSong('cur');
  },
};
</script>

<style lang="less">
.musicContainer {
  position: relative;
  margin-top: 80px;
  padding: 20px 30px;
  height: 100px;
  width: 420px;
  background-color: #fff;
  border-radius: 15px;
  box-shadow: 0 20px 20px 0 rgba(8, 182, 212, 0.822);
  display: flex;
  z-index: 10;
}

.musicInfo {
  position: absolute;
  top: 0;
  left: 30px;
  width: 360px;
  background-color: rgba(255, 255, 255, 0.5);
  border-radius: 15px 15px 0 0;
  padding: 10px 10px 10px 150px;
  opacity: 0;
  transform: translateY(0%);
  transition: transform 0.3s ease-in, opacity 0.3s ease-in;

  .musicTitle {
    font-size: 16px;
    line-height: 22px;
  }

  .progressContainer {
    margin: 10px 0;
    height: 4px;
    width: 100%;
    background-color: #fff;
    border-radius: 5px;
    cursor: pointer;

    .progress {
      height: 100%;
      width: 0%;
      background-color: #0decfc;
      border-radius: inherit;
      transition: width 0.1s linear;
    }
  }
}

.musicCover {
  position: relative;
  top: -50px;
  width: 110px;
  height: 110px;
  margin-right: 30px;

  &::after {
    content: "";
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 15px;
    height: 15px;
    border-radius: 50%;
    background-color: #fff;
  }

  img {
    height: inherit;
    width: inherit;
    border-radius: 50%;
    object-fit: cover;
    animation: rotate 3s linear infinite;
    animation-play-state: paused;
  }
}

.musicControls {
  width: 200px;
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1;

  .actionBtn {
    background-color: #fff;
    color: #0decfc;
    cursor: pointer;
    font-size: 20px;
    padding: 10px;
    margin: 0 20px;
  }

  .actionBtnBig {
    color: #0cdae9;
    font-size: 30px;
  }
}

// 播放状态
.musicContainer.isPlay {
  .musicInfo {
    opacity: 1;
    transform: translateY(-100%);
  }

  .musicCover {
    img {
      animation-play-state: running;
    }
  }
}

@keyframes rotate {
  from {
    transform: rotate(0);
  }

  to {
    transform: rotate(360deg);
  }
}
</style>

// musicPlayer-react/src/components/musicPlayer.tsx
import styles from '@/styles/musicPlayer.module.less'
import { useState, useEffect, useRef } from 'react'

const MusicPlayer = () => {
  const [isPlay, setIsPlay] = useState(false)
  const [curMusic, setCurMusic] = useState({})
  const [curProgress, setCurProgress] = useState('0')
  const audio = useRef(null)

  // @ts-ignore
  const playSong = () => {
    isPlay ? audio.current.pause() : audio.current.play()
    setIsPlay(!isPlay)
  }

  // @ts-ignore
  const queryMusic = async (cmd: 'pre' | 'next' | 'cur') => {
    let res = await fetch('/api/queryMusic', {
      method: 'POST',
      body: JSON.stringify({ cmd })
    })
    res = await res.json()
    console.log(res);
    cmd !== 'cur' && setIsPlay(true) // 开始时不播放

    setCurMusic(res)
    setTimeout(() => {
      // react重新渲染时，会有获取不到dom的bug...
      audio.current.play()
    });
  }
  const updateProgress = (e) => {
    const {
      duration,
      currentTime
    } = e.target

    const progressPercent = (currentTime / duration) * 100 // 当前播放时长 / 音频总时长
    setCurProgress(`${progressPercent}%`)
  }
  // @ts-ignore
  const setProgress = (e) => {
    const width = document.getElementById('progressContainer').clientWidth
    const clickX = e.nativeEvent.offsetX
    const duration = audio.current.duration // 当前音频的总时长 
    audio.current.currentTime = (clickX / width) * duration // 设置音频播放位置
  }
  useEffect(() => {
    queryMusic('cur')
  }, [])
  return (
    <div
      className={
        `
      ${styles.musicContainer}
      ${isPlay ? styles.isPlay : ''}
      `
      }
    >
      <div className={styles.musicInfo}>
        <div className={styles.musicTitle}>{curMusic.title}</div>
        <div className={styles.progressContainer} id="progressContainer" onClick={(e) =>setProgress(e)}>
          <div className={styles.progress} style={{ width: curProgress }}></div>
        </div>
      </div>
      <div className={styles.musicCover}>
        <img src={curMusic.cover} alt="" />
      </div>
      <div className={styles.musicContrals}>
        <div className={styles.actionBtn} onClick={() => queryMusic('pre')}>
          <i className="fas fa-backward"></i>
        </div>
        <div className={`${styles.actionBtn} ${styles.actionBtnBig}`} onClick={playSong}>
          <i className={`fas ${isPlay ? 'fa-pause' : 'fa-play'}`}></i>
        </div>
        <div className={styles.actionBtn} onClick={() => queryMusic('next')}>
          <i className="fas fa-forward"></i>
        </div>
      </div>
      <audio
        ref={audio}
        src={curMusic.link}
        onTimeUpdate={updateProgress}
        onEnded={() => queryMusic('next')}
      />
    </div>
  )
}

export default MusicPlayer
